__productname__ = "len8"
__version__ = "0.0.0"
__description__ = "A utility for keeping line lengths within PEP 8 standards."
__url__ = "https://github.com/parafoxia/len8"
__docs__ = "https://len8.readthedocs.io/en/latest/"
__author__ = "Ethan Henderson, Jonxslays"
__license__ = "BSD-3-Clause"
__bugtracker__ = "https://github.com/parafoxia/len8/issues"
