name: Publish Package and Artefacts

on:
  release:
    types: [published]

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check version
      run: |
        [[ $(sed -rn 's/__version__ = "(.*)"/v\1/p' len8/__init__.py) == ${{ github.event.release.tag_name }} ]]

  package:
    name: Publish package
    needs: check-version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  artefacts:
    name: Publish artefacts
    needs: check-version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install build

    - name: Build artefacts
      run: python -m build

    - name: Attach artefacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
